name: Build Verification

on:
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.vue"
      - "**/*.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - "**/package.json"
  push:
    branches: ["main"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.vue"
      - "**/*.json"
      - "package.json"
      - "pnpm-lock.yaml"
      - "**/package.json"

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda #v4.1.0
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies (with lockfile update if needed)
        run: |
          pnpm install || pnpm install --no-frozen-lockfile

      - name: Run build
        run: pnpm build

      - name: Type check
        id: typecheck
        continue-on-error: true
        run: |
          echo "::warning::Running TypeScript type checking in warning-only mode"
          if pnpm -r typecheck > typecheck_output.txt 2>&1; then
            echo "has_errors=false" >> $GITHUB_OUTPUT
            echo "errors=" >> $GITHUB_OUTPUT
          else
            echo "has_errors=true" >> $GITHUB_OUTPUT
            echo "errors<<EOF" >> $GITHUB_OUTPUT
            cat typecheck_output.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            echo "::warning::Type check found issues but continuing workflow"
          fi

      - name: Create comment
        if: ${{ github.event_name == 'pull_request' && steps.typecheck.outputs.has_errors == 'true' }}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 #4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ⚠️ TypeScript Type Check Warnings

            The build succeeded, but TypeScript found type issues that should be addressed:

            ```
            ${{ steps.typecheck.outputs.errors }}
            ```

            These warnings won't block the PR from being merged, but fixing them is recommended.
          reactions: |
            warning
            eyes
            sob

      - name: Verify build artifacts
        run: |
          if [ ! -f "dist/plugin_package.zip" ]; then
            echo "Build failed: plugin_package.zip not found"
            exit 1
          fi
